#version 450
#extension GL_GOOGLE_include_directive : enable
#include "common.glsl"

layout(binding = 1) readonly buffer RayGeneratorSSBOIn {
    RayGenerator raygenIn[];
};

layout(binding = 2) buffer PreviousRayGeneratorSSBOIn {
    RayGenerator previousRaygenIn[];
};

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint pixelCount = uint(ubo.width) * uint(ubo.height);
    if (gl_GlobalInvocationID.x >= pixelCount) return;
    previousRaygenIn[gl_GlobalInvocationID.x] = raygenIn[gl_GlobalInvocationID.x];
}
