#version 450
#extension GL_GOOGLE_include_directive : enable
#include "common.glsl"

layout(binding = 1, rgba8) uniform image2D outputImage;

layout(binding = 2, rgba8) uniform image2D rawImage;

layout(binding = 3, rgba8) uniform image2D restirImage;

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

bool right_side_x(int x) {
    return ubo.showdivider != 0 && x > int(ubo.divider);
}

bool restir_enabled_x(int x) {
    return (right_side_x(x) ? ubo.restirright : ubo.restir) != 0;
}

void main() {
    uint pixelCount = uint(ubo.width) * uint(ubo.height);
    if (gl_GlobalInvocationID.x >= pixelCount) return;
	int rx = int(gl_GlobalInvocationID.x%int(ubo.width));
    int ry = int(gl_GlobalInvocationID.x/int(ubo.width));
    if (ubo.showdivider != 0 && abs(int(ubo.divider) - rx) < 1) {
        imageStore(outputImage, ivec2(rx, ry), vec4(1));
    } else if (restir_enabled_x(rx)) {
        imageStore(outputImage, ivec2(rx, ry), imageLoad(restirImage, ivec2(rx, ry)));
    } else {
        imageStore(outputImage, ivec2(rx, ry), imageLoad(rawImage, ivec2(rx, ry)));
    }
}
